// src/config/academics.js
export const universitiesData = [
  /* =======================
     PUBLIC UNIVERSITIES
  ======================= */
  { id: "uni_001", name: "University of Nairobi", type: "public" },
  { id: "uni_002", name: "Kenyatta University", type: "public" },
  { id: "uni_003", name: "Moi University", type: "public" },
  {
    id: "uni_004",
    name: "Jomo Kenyatta University of Agriculture and Technology",
    type: "public",
  },
  { id: "uni_005", name: "Egerton University", type: "public" },
  { id: "uni_006", name: "Maseno University", type: "public" },
  {
    id: "uni_007",
    name: "Masinde Muliro University of Science and Technology",
    type: "public",
  },
  { id: "uni_008", name: "Technical University of Kenya", type: "public" },
  { id: "uni_009", name: "Technical University of Mombasa", type: "public" },
  { id: "uni_010", name: "Multimedia University of Kenya", type: "public" },
  {
    id: "uni_011",
    name: "Dedan Kimathi University of Technology",
    type: "public",
  },
  { id: "uni_012", name: "Chuka University", type: "public" },
  { id: "uni_013", name: "Kibabii University", type: "public" },
  { id: "uni_014", name: "Laikipia University", type: "public" },
  { id: "uni_015", name: "Machakos University", type: "public" },
  { id: "uni_016", name: "Maasai Mara University", type: "public" },
  { id: "uni_017", name: "Pwani University", type: "public" },
  { id: "uni_018", name: "South Eastern Kenya University", type: "public" },
  { id: "uni_019", name: "Taita Taveta University", type: "public" },
  { id: "uni_020", name: "University of Eldoret", type: "public" },
  { id: "uni_021", name: "University of Embu", type: "public" },
  { id: "uni_022", name: "University of Kabianga", type: "public" },
  { id: "uni_023", name: "Karatina University", type: "public" },
  { id: "uni_024", name: "Kirinyaga University", type: "public" },
  {
    id: "uni_025",
    name: "Meru University of Science and Technology",
    type: "public",
  },
  { id: "uni_026", name: "Rongo University", type: "public" },
  { id: "uni_027", name: "Kisii University", type: "public" },
  { id: "uni_028", name: "Garissa University", type: "public" },
  { id: "uni_029", name: "Alupe University", type: "public" },
  { id: "uni_030", name: "Co-operative University of Kenya", type: "public" },
  { id: "uni_031", name: "Murang’a University of Technology", type: "public" },
  { id: "uni_032", name: "Open University of Kenya", type: "public" },
  {
    id: "uni_033",
    name: "National Defence University – Kenya",
    type: "public",
  },

  /* =======================
     PRIVATE UNIVERSITIES
  ======================= */
  { id: "uni_101", name: "Strathmore University", type: "private" },
  {
    id: "uni_102",
    name: "United States International University – Africa (USIU-A)",
    type: "private",
  },
  { id: "uni_103", name: "Aga Khan University", type: "private" },
  { id: "uni_104", name: "Mount Kenya University", type: "private" },
  { id: "uni_105", name: "Kabarak University", type: "private" },
  { id: "uni_106", name: "Africa Nazarene University", type: "private" },
  { id: "uni_107", name: "Daystar University", type: "private" },
  {
    id: "uni_108",
    name: "Catholic University of Eastern Africa",
    type: "private",
  },
  { id: "uni_109", name: "Kenya Methodist University", type: "private" },
  { id: "uni_110", name: "KCA University", type: "private" },
  { id: "uni_111", name: "Management University of Africa", type: "private" },
  { id: "uni_112", name: "Zetech University", type: "private" },
  { id: "uni_113", name: "Pan Africa Christian University", type: "private" },
  { id: "uni_114", name: "Riara University", type: "private" },
  { id: "uni_115", name: "St. Paul’s University", type: "private" },
  { id: "uni_116", name: "Scott Christian University", type: "private" },
  { id: "uni_117", name: "Great Lakes University of Kisumu", type: "private" },
  { id: "uni_118", name: "Umma University", type: "private" },
  { id: "uni_119", name: "Amref International University", type: "private" },

  /* =======================
     NATIONAL COLLEGES & INSTITUTES
  ======================= */
  {
    id: "col_001",
    name: "Kenya Medical Training College (KMTC)",
    type: "college",
  },
  {
    id: "col_002",
    name: "Kenya Institute of Banking and Insurance",
    type: "college",
  },
  { id: "col_003", name: "Kenya School of Law", type: "college" },
  { id: "col_004", name: "Kenya School of Government", type: "college" },
  { id: "col_005", name: "Kenya National Police College", type: "college" },
  {
    id: "col_006",
    name: "Kenya Institute of Mass Communication",
    type: "college",
  },
  { id: "col_007", name: "Kenya Utalii College", type: "college" },
  { id: "col_008", name: "East Africa School of Aviation", type: "college" },

  /* =======================
     MAJOR TVET INSTITUTES
  ======================= */
  {
    id: "tvet_001",
    name: "Nairobi Technical Training Institute",
    type: "training_institute",
  },
  {
    id: "tvet_002",
    name: "Kabete National Polytechnic",
    type: "training_institute",
  },
  {
    id: "tvet_003",
    name: "Rift Valley Technical Training Institute",
    type: "training_institute",
  },
  {
    id: "tvet_004",
    name: "Eldoret National Polytechnic",
    type: "training_institute",
  },
  {
    id: "tvet_005",
    name: "Meru National Polytechnic",
    type: "training_institute",
  },
  {
    id: "tvet_006",
    name: "Nyeri National Polytechnic",
    type: "training_institute",
  },
  {
    id: "tvet_007",
    name: "Kisumu National Polytechnic",
    type: "training_institute",
  },
  {
    id: "tvet_008",
    name: "Mombasa Technical Training Institute",
    type: "training_institute",
  },
];

export const departmentsData = [
  { id: "dept_001", name: "Computer Science", category: "computing" },
  { id: "dept_002", name: "Information Technology", category: "computing" },
  { id: "dept_003", name: "Software Engineering", category: "computing" },
  { id: "dept_004", name: "Data Science", category: "computing" },
  { id: "dept_005", name: "Cyber Security", category: "computing" },
  { id: "dept_006", name: "Information Systems", category: "computing" },
  { id: "dept_010", name: "Civil Engineering", category: "engineering" },
  {
    id: "dept_011",
    name: "Electrical & Electronic Engineering",
    category: "engineering",
  },
  { id: "dept_012", name: "Mechanical Engineering", category: "engineering" },
  { id: "dept_013", name: "Mechatronics Engineering", category: "engineering" },
  { id: "dept_014", name: "Chemical Engineering", category: "engineering" },
  {
    id: "dept_015",
    name: "Telecommunication Engineering",
    category: "engineering",
  },
  { id: "dept_016", name: "Industrial Engineering", category: "engineering" },
  { id: "dept_020", name: "Medicine & Surgery", category: "health" },
  { id: "dept_021", name: "Nursing", category: "health" },
  { id: "dept_022", name: "Clinical Medicine", category: "health" },
  { id: "dept_023", name: "Public Health", category: "health" },
  { id: "dept_024", name: "Pharmacy", category: "health" },
  { id: "dept_025", name: "Medical Laboratory Sciences", category: "health" },
  { id: "dept_026", name: "Radiography & Imaging", category: "health" },
  { id: "dept_027", name: "Dental Technology", category: "health" },
  { id: "dept_030", name: "Business Administration", category: "business" },
  { id: "dept_031", name: "Commerce", category: "business" },
  { id: "dept_032", name: "Accounting", category: "business" },
  { id: "dept_033", name: "Finance", category: "business" },
  { id: "dept_034", name: "Economics", category: "business" },
  {
    id: "dept_035",
    name: "Procurement & Supply Chain Management",
    category: "business",
  },
  { id: "dept_036", name: "Human Resource Management", category: "business" },
  { id: "dept_037", name: "Entrepreneurship", category: "business" },
  { id: "dept_040", name: "Law", category: "law" },
  { id: "dept_041", name: "Criminology & Security Studies", category: "law" },
  { id: "dept_042", name: "International Relations", category: "law" },
  { id: "dept_043", name: "Public Administration", category: "law" },
  { id: "dept_044", name: "Political Science", category: "law" },
  { id: "dept_050", name: "Education (Arts)", category: "education" },
  { id: "dept_051", name: "Education (Science)", category: "education" },
  {
    id: "dept_052",
    name: "Early Childhood Development Education",
    category: "education",
  },
  { id: "dept_053", name: "Special Needs Education", category: "education" },
  { id: "dept_054", name: "Educational Management", category: "education" },
  { id: "dept_060", name: "Agriculture", category: "agriculture" },
  { id: "dept_061", name: "Agribusiness Management", category: "agriculture" },
  { id: "dept_062", name: "Animal Science", category: "agriculture" },
  { id: "dept_063", name: "Horticulture", category: "agriculture" },
  { id: "dept_064", name: "Environmental Science", category: "agriculture" },
  { id: "dept_065", name: "Forestry", category: "agriculture" },
  {
    id: "dept_066",
    name: "Food Science & Technology",
    category: "agriculture",
  },
  { id: "dept_070", name: "Journalism & Mass Communication", category: "arts" },
  { id: "dept_071", name: "Film & Theatre Arts", category: "arts" },
  { id: "dept_072", name: "Communication & Media Studies", category: "arts" },
  { id: "dept_073", name: "Fine Art & Design", category: "arts" },
  { id: "dept_074", name: "Music", category: "arts" },
  { id: "dept_075", name: "Linguistics", category: "arts" },
  { id: "dept_080", name: "Sociology", category: "social" },
  { id: "dept_081", name: "Psychology", category: "social" },
  { id: "dept_082", name: "Social Work", category: "social" },
  { id: "dept_083", name: "Community Development", category: "social" },
  { id: "dept_084", name: "Development Studies", category: "social" },
  { id: "dept_090", name: "Hospitality Management", category: "hospitality" },
  { id: "dept_091", name: "Tourism Management", category: "hospitality" },
  {
    id: "dept_092",
    name: "Hotel & Catering Management",
    category: "hospitality",
  },
  { id: "dept_093", name: "Sports Science", category: "hospitality" },
  { id: "dept_100", name: "Building Construction", category: "tvet" },
  { id: "dept_101", name: "Automotive Engineering", category: "tvet" },
  { id: "dept_102", name: "Electrical Installation", category: "tvet" },
  { id: "dept_103", name: "Plumbing & Pipe Fitting", category: "tvet" },
  { id: "dept_104", name: "Welding & Fabrication", category: "tvet" },
  { id: "dept_105", name: "Fashion Design", category: "tvet" },
];

export const levelsData = [
  { id: "level_cert", name: "Certificate", category: "tvet" },
  { id: "level_adv_cert", name: "Advanced Certificate", category: "tvet" },
  { id: "level_dip", name: "Diploma", category: "tvet" },
  { id: "level_high_dip", name: "Higher Diploma", category: "tvet" },
  {
    id: "level_deg_yr1",
    name: "Bachelor's Degree – Year 1",
    category: "undergraduate",
  },
  {
    id: "level_deg_yr2",
    name: "Bachelor's Degree – Year 2",
    category: "undergraduate",
  },
  {
    id: "level_deg_yr3",
    name: "Bachelor's Degree – Year 3",
    category: "undergraduate",
  },
  {
    id: "level_deg_yr4",
    name: "Bachelor's Degree – Year 4",
    category: "undergraduate",
  },
  {
    id: "level_deg_yr5",
    name: "Bachelor's Degree – Year 5 (where applicable)",
    category: "undergraduate",
  },
  {
    id: "level_pg_dip",
    name: "Postgraduate Diploma",
    category: "postgraduate",
  },
  { id: "level_masters", name: "Master's Degree", category: "postgraduate" },
  {
    id: "level_phd",
    name: "Doctor of Philosophy (PhD)",
    category: "postgraduate",
  },
];

export const coursesData = [
  {
    id: "course_comp_sci_101",
    name: "Introduction to Computer Science",
    department_id: "dept_001",
  },
  { id: "course_web_dev", name: "Web Development", department_id: "dept_002" },
  {
    id: "course_data_structures",
    name: "Data Structures & Algorithms",
    department_id: "dept_001",
  },
  {
    id: "course_machine_learning",
    name: "Machine Learning",
    department_id: "dept_004",
  },
  {
    id: "course_cyber_security",
    name: "Cyber Security Fundamentals",
    department_id: "dept_005",
  },
  {
    id: "course_software_eng",
    name: "Software Engineering Principles",
    department_id: "dept_003",
  },
  {
    id: "course_database_systems",
    name: "Database Systems",
    department_id: "dept_006",
  },
  {
    id: "course_computer_networks",
    name: "Computer Networks",
    department_id: "dept_002",
  },
  {
    id: "course_artificial_intelligence",
    name: "Artificial Intelligence",
    department_id: "dept_004",
  },
  {
    id: "course_mobile_app_dev",
    name: "Mobile Application Development",
    department_id: "dept_003",
  },
  {
    id: "course_civil_engineering",
    name: "Civil Engineering Principles",
    department_id: "dept_010",
  },
  {
    id: "course_electrical_basics",
    name: "Electrical Engineering Basics",
    department_id: "dept_011",
  },
  {
    id: "course_mechanics",
    name: "Engineering Mechanics",
    department_id: "dept_012",
  },
  {
    id: "course_thermodynamics",
    name: "Thermodynamics",
    department_id: "dept_012",
  },
  {
    id: "course_circuit_analysis",
    name: "Circuit Analysis",
    department_id: "dept_011",
  },
  {
    id: "course_structural_analysis",
    name: "Structural Analysis",
    department_id: "dept_010",
  },
  {
    id: "course_mechanical_design",
    name: "Mechanical Design",
    department_id: "dept_012",
  },
  {
    id: "course_control_systems",
    name: "Control Systems",
    department_id: "dept_013",
  },
  {
    id: "course_chemical_processes",
    name: "Chemical Processes",
    department_id: "dept_014",
  },
  {
    id: "course_telecom_networks",
    name: "Telecommunication Networks",
    department_id: "dept_015",
  },
  {
    id: "course_business_admin",
    name: "Business Administration",
    department_id: "dept_030",
  },
  {
    id: "course_accounting_101",
    name: "Financial Accounting",
    department_id: "dept_032",
  },
  {
    id: "course_marketing",
    name: "Marketing Principles",
    department_id: "dept_030",
  },
  {
    id: "course_microeconomics",
    name: "Microeconomics",
    department_id: "dept_034",
  },
  {
    id: "course_management_principles",
    name: "Management Principles",
    department_id: "dept_030",
  },
  {
    id: "course_corporate_finance",
    name: "Corporate Finance",
    department_id: "dept_033",
  },
  {
    id: "course_supply_chain",
    name: "Supply Chain Management",
    department_id: "dept_035",
  },
  {
    id: "course_human_resources",
    name: "Human Resource Management",
    department_id: "dept_036",
  },
  {
    id: "course_business_law",
    name: "Business Law",
    department_id: "dept_040",
  },
  {
    id: "course_entrepreneurship",
    name: "Entrepreneurship",
    department_id: "dept_037",
  },
  { id: "course_anatomy", name: "Human Anatomy", department_id: "dept_020" },
  {
    id: "course_nursing_fundamentals",
    name: "Nursing Fundamentals",
    department_id: "dept_021",
  },
  {
    id: "course_pharmacology",
    name: "Pharmacology",
    department_id: "dept_024",
  },
  { id: "course_pathology", name: "Pathology", department_id: "dept_020" },
  {
    id: "course_medical_ethics",
    name: "Medical Ethics",
    department_id: "dept_020",
  },
  {
    id: "course_clinical_practice",
    name: "Clinical Practice",
    department_id: "dept_022",
  },
  {
    id: "course_public_health",
    name: "Public Health",
    department_id: "dept_023",
  },
  {
    id: "course_medical_lab",
    name: "Medical Laboratory Techniques",
    department_id: "dept_025",
  },
  { id: "course_radiology", name: "Radiology", department_id: "dept_026" },
  {
    id: "course_dental_science",
    name: "Dental Science",
    department_id: "dept_027",
  },
  {
    id: "course_psychology_101",
    name: "Introduction to Psychology",
    department_id: "dept_081",
  },
  { id: "course_sociology", name: "Sociology", department_id: "dept_080" },
  {
    id: "course_social_work",
    name: "Social Work Practice",
    department_id: "dept_082",
  },
  { id: "course_criminology", name: "Criminology", department_id: "dept_041" },
  {
    id: "course_political_science",
    name: "Political Science",
    department_id: "dept_044",
  },
  {
    id: "course_international_relations",
    name: "International Relations",
    department_id: "dept_042",
  },
  {
    id: "course_development_studies",
    name: "Development Studies",
    department_id: "dept_084",
  },
  {
    id: "course_community_dev",
    name: "Community Development",
    department_id: "dept_083",
  },
  { id: "course_linguistics", name: "Linguistics", department_id: "dept_075" },
  {
    id: "course_anthropology",
    name: "Cultural Anthropology",
    department_id: "dept_080",
  },
  { id: "course_journalism", name: "Journalism", department_id: "dept_070" },
  {
    id: "course_communication",
    name: "Communication Studies",
    department_id: "dept_072",
  },
  {
    id: "course_film_studies",
    name: "Film Studies",
    department_id: "dept_071",
  },
  { id: "course_fine_art", name: "Fine Art", department_id: "dept_073" },
  {
    id: "course_music_theory",
    name: "Music Theory",
    department_id: "dept_074",
  },
  {
    id: "course_literature",
    name: "English Literature",
    department_id: "dept_075",
  },
  { id: "course_philosophy", name: "Philosophy", department_id: "dept_075" },
  { id: "course_history", name: "History", department_id: "dept_075" },
  {
    id: "course_theatre_arts",
    name: "Theatre Arts",
    department_id: "dept_071",
  },
  {
    id: "course_digital_media",
    name: "Digital Media",
    department_id: "dept_072",
  },
  {
    id: "course_educational_psychology",
    name: "Educational Psychology",
    department_id: "dept_050",
  },
  {
    id: "course_curriculum_dev",
    name: "Curriculum Development",
    department_id: "dept_054",
  },
  {
    id: "course_teaching_methods",
    name: "Teaching Methods",
    department_id: "dept_050",
  },
  {
    id: "course_early_childhood",
    name: "Early Childhood Education",
    department_id: "dept_052",
  },
  {
    id: "course_special_education",
    name: "Special Education",
    department_id: "dept_053",
  },
  {
    id: "course_educational_admin",
    name: "Educational Administration",
    department_id: "dept_054",
  },
  {
    id: "course_science_education",
    name: "Science Education",
    department_id: "dept_051",
  },
  {
    id: "course_math_education",
    name: "Mathematics Education",
    department_id: "dept_051",
  },
  {
    id: "course_language_teaching",
    name: "Language Teaching",
    department_id: "dept_050",
  },
  {
    id: "course_educational_tech",
    name: "Educational Technology",
    department_id: "dept_054",
  },
  { id: "course_agronomy", name: "Agronomy", department_id: "dept_060" },
  {
    id: "course_animal_husbandry",
    name: "Animal Husbandry",
    department_id: "dept_062",
  },
  {
    id: "course_horticulture",
    name: "Horticulture",
    department_id: "dept_063",
  },
  {
    id: "course_environmental_science",
    name: "Environmental Science",
    department_id: "dept_064",
  },
  { id: "course_forestry", name: "Forestry", department_id: "dept_065" },
  {
    id: "course_food_technology",
    name: "Food Technology",
    department_id: "dept_066",
  },
  {
    id: "course_agribusiness",
    name: "Agribusiness Management",
    department_id: "dept_061",
  },
  {
    id: "course_soil_science",
    name: "Soil Science",
    department_id: "dept_060",
  },
  {
    id: "course_water_resources",
    name: "Water Resources Management",
    department_id: "dept_064",
  },
  {
    id: "course_climate_change",
    name: "Climate Change Studies",
    department_id: "dept_064",
  },
  {
    id: "course_hotel_management",
    name: "Hotel Management",
    department_id: "dept_090",
  },
  {
    id: "course_tourism_management",
    name: "Tourism Management",
    department_id: "dept_091",
  },
  {
    id: "course_catering",
    name: "Catering Management",
    department_id: "dept_092",
  },
  {
    id: "course_event_management",
    name: "Event Management",
    department_id: "dept_090",
  },
  {
    id: "course_sports_management",
    name: "Sports Management",
    department_id: "dept_093",
  },
  {
    id: "course_travel_agency",
    name: "Travel Agency Operations",
    department_id: "dept_091",
  },
  {
    id: "course_food_beverage",
    name: "Food & Beverage Management",
    department_id: "dept_092",
  },
  {
    id: "course_recreation",
    name: "Recreation Management",
    department_id: "dept_093",
  },
  {
    id: "course_hospitality_law",
    name: "Hospitality Law",
    department_id: "dept_090",
  },
  {
    id: "course_tourism_impact",
    name: "Tourism Impact Assessment",
    department_id: "dept_091",
  },
  {
    id: "course_building_construction",
    name: "Building Construction",
    department_id: "dept_100",
  },
  {
    id: "course_automotive_repair",
    name: "Automotive Repair",
    department_id: "dept_101",
  },
  {
    id: "course_electrical_installation",
    name: "Electrical Installation",
    department_id: "dept_102",
  },
  {
    id: "course_plumbing",
    name: "Plumbing & Pipe Fitting",
    department_id: "dept_103",
  },
  {
    id: "course_welding",
    name: "Welding & Fabrication",
    department_id: "dept_104",
  },
  {
    id: "course_fashion_design",
    name: "Fashion Design",
    department_id: "dept_105",
  },
  { id: "course_carpentry", name: "Carpentry", department_id: "dept_100" },
  { id: "course_masonry", name: "Masonry", department_id: "dept_100" },
  {
    id: "course_motorcycle_mechanics",
    name: "Motorcycle Mechanics",
    department_id: "dept_101",
  },
  {
    id: "course_refrigeration",
    name: "Refrigeration & Air Conditioning",
    department_id: "dept_102",
  },
];

export default { universitiesData, departmentsData, levelsData, coursesData };
